---
  - hosts: ubuntu
    become: yes
    tasks:
      - name: This will update cache
        apt:
          name: update
          update_cache: yes
      - name: This will install apache
        apt:
          name: apache2
          state: present